apiVersion: apps/v1
kind: Deployment
metadata:
  name: sedetosdevops
  labels:
    app: sedetosdevops
spec:
  replicas: 5
  selector:
    matchLabels:
      app: sedetosdevops
  template:
    metadata:
      labels:
        app: sedetosdevops
    spec:
      containers:
      - name: sedetosdevops
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
